# Label rules based on skills
skill:Python:
  - "Python"
skill:JavaScript:
  - "JavaScript"
skill:TypeScript:
  - "TypeScript"
skill:Machine Learning:
  - "Machine Learning"
skill:NLP:
  - "NLP"

# Label rules based on time commitment
time:low:
  - "Low (1-3 hours/week)"
time:medium:
  - "Medium (4-8 hours/week)"
time:high:
  - "High (8+ hours/week)"
