blank_issues_enabled: false
contact_links:
  - name: SAP AI Guild Discussions
    url: https://github.com/sap-ai-guild/discussions
    about: Please ask and answer questions here.
  - name: SAP AI Guild Documentation
    url: https://github.com/sap-ai-guild/docs
    about: Check our documentation for guides on contributing.
